### ISSUE TITLE
ABI version mismatch

### ISSUE THREAD

**Issue by ghost** [cryptodotis/irssi-otr#62]
`'Irssi: otr/otr is ABI version 0 but Irssi is version 1, cannot load`

I'm using irssi 0.8.18 and irssi-otr 1.0.0 on Arch Linux. This was all working a couple of weeks ago.

**Comment by anarcat** [comment]
this is affecting all debian testing (and above) users as well: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=818590

i think the short fix is just to rebuild the plugin. to quote the Debian bug report above:

> irssi needs to arrange to provide a virtual package, e.g. irssi-abi-1
> and must ensure that plugins pick up a proper dependency on this virtual
> package. Once the abi changes (and the virtual package is renamed), this
> will visibly trigger a transition.
> 
> There are several packages in the archive doing this, I think proftpd is
> one of them.

**Comment by dgoulet** [comment]
Hopefully fixed with #62

**Comment by calumats** [comment]
I can confirm the latest master fixes this issue for me.

**Comment by anarcat** [comment]
i have uploaded a new version in debian sid that, according to my friendly testers, fixes the issue as well.

**Comment by Eluvatar** [comment]
This problem now happens on fedora.

**Comment by VERTlG0** [comment]
I'm having this issue on Gentoo as well with irssi v0.8.20-r1 and irssi-otr v1.0.0-r1 in Portage Package Manager. I updated irssi-otr-1.0.0-r1 to pull in irssi-otr-1.0.1 but seems i still get the error about the ABI version. Is there a newer version than irssi-otr-1.0.1?  I guessed at the version number when doing the ebuild, but it seemed to pull in a tar for it.

**Comment by dominic-miglar** [comment]
`irssi 0.8.20 (20160914 1355)` here. I have the same problem.

**Comment by dgoulet** [comment]
I just pushed v1.0.2 with the ABI fix. Make sure to install `libotr.so` in the `modules/` directory so irssi can call the right abicheck that is "otr_abicheck()". For some reasons, irssi also triese `libotr_core.so` but that will fail so the package must really install `libotr.so`

**Comment by anarcat** [comment]
On 2016-12-07 16:26:31, David Goulet wrote:
> I just pushed v1.0.2 with the ABI fix. Make sure to install `libotr.so` in the `modules/` directory so irssi can call the right abicheck that is "otr_abicheck()". For some reasons, irssi also triese `libotr_core.so` but that will fail so the package must really install `libotr.so`

I'll keep that in mind. Normally, other debian maintainers can package
that update, but I suspect I'll be the one doing this if no one does
before january.

-- 
The future is already here – it's just not very evenly distributed.
                       - William Gibson

**Comment by traumschule** [comment]
Hi and HNY! Just ran into this after recompiling irssi. With above info i should be able to figure it out but i'm afraid i'm not for ea5b8e09506a1d6c7bb51651e19fa1165e373c61:

```
/load otr
-!- Irssi: otr/otr is ABI version 13 but Irssi is version 19, cannot load

$ irssi --version
irssi 1.2-gc7ce0f32 (20181218 2053)

irssi-libotr$ make install
...
libtool: install: /usr/bin/install -c .libs/libotr.so /home/traumschule/usr/lib/irssi/modules/libotr.so

$ ls -l ~/.irssi/modules/libotr.so
lrwxrwxrwx 1 traumschule users 49 20. Dez 2017  /home/traumschule/.irssi/modules/libotr.so -> /home/traumschule/usr/lib/irssi/modules/libotr.so

$ ls -lh /home/traumschule/usr/lib/irssi/modules/libotr.so
-rw-r--r-- 1 traumschule users 275K  7. Jan 15:15 /home/traumschule/usr/lib/irssi/modules/libotr.so

$ file ~/usr/lib/irssi/modules/libotr.so
/home/traumschule/usr/lib/irssi/modules/libotr.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, with debug_info, not stripped

/load otr
-!- Irssi: otr/otr is ABI version 13 but Irssi is version 19, cannot load
```

And with a new profile:
```
mkdir -p new/modules
cp ~/usr/lib/irssi/modules/libotr.so new/modules
irssi --home new
 Irssi v1.2-gc7ce0f32 - https://irssi.org                                                                       
15:46 -!-  ___           _
15:46 -!- |_ _|_ _ _____(_)
15:46 -!-  | || '_(_-<_-< |
15:46 -!- |___|_| /__/__/_|
15:46 -!- Irssi v1.2-gc7ce0f32 - https://irssi.org
15:46 -!- Irssi: otr/otr is ABI version 13 but Irssi is version 19, cannot load
```

**Comment by traumschule** [comment]
In #irssi i was told to just compile irssi with `./configure --with-otr` and it worked.

**Comment by Rhialto** [comment]
I just tried that with the latest released version from the website https://irssi.org/download/ (1.1.2) and configure did not recognize that option.

**Comment by traumschule** [comment]
It's only in git so far and will be in 1.2, see https://github.com/irssi/irssi/issues/881
